language: cpp
compiler: gcc

before_script:
        # create a build folder for the out-of source-build
        - mkdir build
        # switch to build dir
        - cd build
        # run cmake, that is located in top-level dir
        - cmake ..
        - cmake --build .
        - cmake --build . --target package

script:
        - make

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T cmake_train-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -udustydumb:$BINTRAY_API_KEY "https://api.bintray.com/content/dustydumb/otus_tasks/ip_sort/$TRAVIS_BUILD_NUMBER/cmake_train-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

